# Generated by Django 6.0.dev20250709161004 on 2025-07-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0003_formsubmission_prediction_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='name',
        ),
    ]
