# Generated by Django 6.0.dev20250709161004 on 2025-07-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0004_remove_formsubmission_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='similar_case_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Similar Case ID'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Similarity Score'),
        ),
    ]
